Test_DataObject's public $db breaks unit tests
fixes this error: 

LogicException: SilverStripe\GoogleSitemaps\Test_DataObject::db is not private but overrides a private static config in parent class SilverStripe\ORM\DataObject